# app/graphql/types/author_type.rb
module Types
  class AuthorType < Types::BaseObject # <-- Inherits from the base generated by the installer
    description "A blog author"

    field :id, ID, null: false
    field :name, String, null: true # Changed to true to match Rails default validation (or add presence validation)
    field :email, String, null: true
    field :created_at, GraphQL::Types::ISO8601DateTime, null: false # Rails timestamps!
    field :updated_at, GraphQL::Types::ISO8601DateTime, null: false

    # How can we expose the posts written by this author?
    # We'll add this next!
    field :posts, [ Types::PostType ], null: false

    def posts
      # dataloader.with(Loaders::AssociationLoader, Author, :posts).load(object)
      Loaders::AssociationLoaderForBatch.for(::Author, :posts).load(object)

    end
  end
end
